// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef PRIVACY_NET_COMMON_CPP_PUBLIC_METADATA_SERIALIZE_H_
#define PRIVACY_NET_COMMON_CPP_PUBLIC_METADATA_SERIALIZE_H_

#include <cstdint>
#include <string>

#include "third_party/absl/strings/string_view.h"

namespace privacy::ppn {

// Converts an 8-byte uint64_t to a string such that the string keys sort in
// the same order as the original uint64_t value.
void BytesFromUint64(uint64_t fp, std::string* key);

// Convenient form of KeyFromUint64.
std::string Uint64ToBytes(uint64_t fp);

// Converts an 8-byte string key (typically generated by Uint64ToKey or
// KeyFromUint64) into a uint64_t value
uint64_t BytesToUint64(absl::string_view key);

}  // namespace privacy::ppn

#endif  // PRIVACY_NET_COMMON_CPP_PUBLIC_METADATA_SERIALIZE_H_
